services:
  db:
    container_name: postgres
    image: postgres:15.6-alpine3.19
    restart: always
    env_file:
      - dev.env

    hostname: postgres
    networks:
        - gocom
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - gocom
    env_file:
      - dev.env


  product-service:
    container_name: productcont
    restart: on-failure
    hostname: product
    build:
      context: .
      dockerfile: product/Dockerfile
    env_file:
      - dev.env
    networks:
        - gocom
    ports:
      - "4001:4001"
    depends_on:
      - db
      - rabbit


networks:
  gocom:

volumes:
  postgres_data:

